/*
 * Фильмотека API
 *
 * API Фильмотеки
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"database/sql"
	"log"
	"net/http"

	sw "./go"
	_ "github.com/lib/pq"
)

func main() {
	log.Printf("Server started")
	db, err := sql.Open("postgres", "user=youruser dbname=yourdb sslmode=disable")
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}
	defer db.Close()

	router := sw.NewRouter(db)

	log.Fatal(http.ListenAndServe(":8080", router))
}
