/*
 * Фильмотека API
 *
 * API Фильмотеки
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Movie struct {

	Id string `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Description string `json:"description,omitempty"`

	ReleaseDate string `json:"release_date,omitempty"`

	Rating int32 `json:"rating,omitempty"`

	Actors *ActorList `json:"actors,omitempty"`
}
