/*
 * Фильмотека API
 *
 * API Фильмотеки
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Gender string

// List of Gender
const (
	EMPTY Gender = ""
	MALE Gender = "male"
	FEMALE Gender = "female"
)
